name: "Docker update description"

on:
  push:
    paths:
      - "README.md"
    branches:
      - "main"

jobs:
  docker:
    name: "Docker update description"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: adlacruzes/node-ci
